title: Josh Nielson # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  WGU Master's in Data Analytics specializing in machine learning.
  <br><br>
  Experienced QA engineer, product expert and cryptocurrency investor.
  <br><br>
  <a href="https://www.linkedin.com/in/josh-nielson/">LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/joshnielson">GitHub Profile</a> 
  
theme: jekyll-theme-minimal
